// Font Awesome Configuration
import { library } from '@fortawesome/fontawesome-svg-core';

// Import solid icons
import {
  faBars,
  faPhone,
  faEnvelope,
  faMapMarkerAlt,
  faHome,
  faSearch,
  faUserPlus,
  faCog,
  faSignOutAlt,
  faEye,
  faDownload,
  faEdit,
  faTrash,
  faPlus,
  faFilter,
  faSort,
  faSortUp,
  faSortDown,
  faCalendarPlus,
  faCalendarCheck,
  faHashtag,
  faInfoCircle,
  faCheckCircle,
  faTimesCircle,
  faExclamationTriangle,
  faSpinner,
  faHeart,
  faStar,
  faUser,
  faUsers,
  faBuilding,
  faBriefcase,
  faGraduationCap,
  faLanguage,
  faTools,
  faCalendar,
  faCircleUser,
  faArrowRightFromBracket,
  faGear,
  faWifi,
  faUpload,
  faPencil,
  faArrowUp,
  faArrowDown,
  faChevronUp,
  faChevronDown
} from '@fortawesome/free-solid-svg-icons';

// Import brand icons
import {
  faFacebookF,
  faTwitter,
  faInstagram,
  faLinkedin,
  faWhatsapp
} from '@fortawesome/free-brands-svg-icons';

// Add icons to the library
library.add(
  // Solid icons
  faBars,
  faPhone,
  faEnvelope,
  faMapMarkerAlt,
  faHome,
  faSearch,
  faUserPlus,
  faCog,
  faSignOutAlt,
  faEye,
  faDownload,
  faEdit,
  faTrash,
  faPlus,
  faFilter,
  faSort,
  faSortUp,
  faSortDown,
  faCalendarPlus,
  faCalendarCheck,
  faHashtag,
  faInfoCircle,
  faCheckCircle,
  faTimesCircle,
  faExclamationTriangle,
  faSpinner,
  faHeart,
  faStar,
  faUser,
  faUsers,
  faBuilding,
  faBriefcase,
  faGraduationCap,
  faLanguage,
  faTools,
  faCalendar,
  faCircleUser,
  faArrowRightFromBracket,
  faGear,
  faWifi,
  faUpload,
  faPencil,
  faArrowUp,
  faArrowDown,
  faChevronUp,
  faChevronDown,
  
  // Brand icons
  faFacebookF,
  faTwitter,
  faInstagram,
  faLinkedin,
  faWhatsapp
);